<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  </configSections>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.SqlConnectionFactory, EntityFramework" />
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
    </providers>
  </entityFramework>
  <connectionStrings>
    <add name="ExceptionDatabaseConnection" connectionString="data source=SITEFUEL-011-KS\SQLEXPRESS01;initial catalog=Exceptions-QA;integrated security=False;user id=sa;password=First#1234;pooling=True;max pool size=100;multipleactiveresultsets=True;connect timeout=30;encrypt=False;trustservercertificate=True;application name=EntityFramework;applicationintent=ReadWrite;multisubnetfailover=False" providerName="System.Data.SqlClient"/>
  </connectionStrings>
</configuration>